site_name: Appli Documentation
nav:
    - Home: index.md
    - Action Types:
        - Bi-entity Action Types: types/bientity_action_types.md
        - Entity Action Types: types/entity_action_types.md
    - Condition Types:
        - Bi-entity Condition Types: types/bientity_condition_types.md
        - Block Condition Types: types/block_condition_types.md
        - Entity Condition Types: types/entity_condition_types.md
    - General Types:
        - Data Types: types/data_types.md
        - Power Types: types/power_types.md

theme: readthedocs
markdown_extensions:
    - toc:
        separator: "_"
    - admonition
